### ISSUE TITLE
Implement `add` action

### ISSUE THREAD

**Issue by wevtimoteo** [elixirsc/git-pair#4]
To mark who is pairing with, we need to add ability to user pass GitHub usernames and register them in `.git/config`:

```
git config --add pair.coauthor github-username
```

We should implement a wrapper for the command above using our binary:

```
git pair add github-username
```

Doesn’t seem to be a limit on the number of co-authors, but we need to check if GitHub can limit the displayed User avatars in commit listing.

**Comment by amadeu01** [comment]
We will not validate the username. (At least for now)
