### ISSUE TITLE
Implement `status` action

### ISSUE THREAD

**Issue by wevtimoteo** [elixirsc/git-pair#6]
To know who is pairing with, we need to add ability to user list registered usernames under from `.git/config`:

```
git config --get-all pair.coauthor
```

More details about `--get-all` can be found in [`Git docs`](https://git-scm.com/docs/git-config#Documentation/git-config.txt---get-all).

We should implement a wrapper for the command above using our binary:

```
git pair status
```

I was thinking if we should create an alias for it, maybe `git pair list`. WDYT?

**Comment by lcidral** [comment]
As suggested by @amadeu01, we can leave `git pair list` reserved to list team members or potential users that developer want to mark as pairing to. WDYT?

**Comment by wevtimoteo** [comment]
@lcidral agreed, we can leave `list` for other action :)

We should write more details about this proposal, @amadeu01 can you describe it in a new issue?

**Comment by amadeu01** [comment]
Sure!
